data:
  seed: 42
  cnn_features_setting:
    frontend_algorithm: []  # ["mfcc"] or ["lfcc"] or ["mfcc", "lfcc"]
    use_spectrogram: False

checkpoint:
  paths: [
  "/kaggle/input/rawnetckpt/ckpt.pth",
  ]

model:
  name: "rawnet"
  parameters: {}
  optimizer:
    lr: 0.0001
    weight_decay: 0.0001
