data:
  seed: 42
  cnn_features_setting:
    frontend_algorithm: []  # ["mfcc"] or ["lfcc"] or ["mfcc", "lfcc"]
    use_spectrogram: False

checkpoint:
  paths: [
  "trained_models/aad__rawnet_fold_0__1716923767.6772423/ckpt.pth",
  "trained_models/aad__rawnet_fold_1__1716912939.4962392/ckpt.pth",
  ]

model:
  name: "rawnet"
  parameters: {}
  optimizer:
    lr: 0.0001
    weight_decay: 0.001
