data:
  seed: 42
  cnn_features_setting:
    frontend_algorithm: []  # ["mfcc"] or ["lfcc"] or ["mfcc", "lfcc"]
    use_spectrogram: False

checkpoint:
  paths: [
  "trained_models/aad__rawnet_fold_0__1717233988.902598/ckpt.pth",
  "trained_models/aad__rawnet_fold_1__1717233988.902598/ckpt.pth",
  ]

model:
  name: "rawnet"
  parameters: {}
  optimizer:
    lr: 0.00001
    weight_decay: 0.0001
